### ISSUE TITLE
A little confusing naming

### ISSUE THREAD

**Issue by JMencius** [paoloshasta/shasta#21]
Hi, developers of Shasta. I found the naming convention in your configuration a bit confusing. 
As far as I understand, '_R10-Fast_' refers to the R10.4.1_400bps sequencing mode, and '_R10-Slow_' refers to the R10.4.1_260bps sequencing mode. However, this may be confusing for beginners who have not read the manual in detail. Someone (including stupid me) may misuse the config under the comprehension that  '_R10-Fast_' and '_R10-Slow_' indicated different speed modes or accuracy mode for Shasta, especially since one of the main advantages is speed. 
I humbly recommend using 'R10-400bps' or 'R10-FAST-400bps' for the configuration file naming. I think it is more clear.

**Comment by paoloshasta** [comment]
That is a valid point, and I agree that the naming you propose would have been better. This situation was created as a result of how these configurations came to be. I created them when the two sequencing modes very still very new and naming was still unsettled, and the groups I worked with referred to them as "slow mode" and "fast mode". The situation was further complicated by the fact that ONT later abandoned the "slow" (260bps) mode.

Unfortunately, renaming them at this point would further increase the confusion, and so I think I will leave the names as they are. However, for new configurations in future releases, I will simply use "R10" in the configuration name, without additional qualifications. 

Also, for future reference, keep in mind that you can always look at the details of an assembly configuration using the following command:

```
shasta --command listConfiguration --config configurationName
```

This will list all option values different from default, and more importantly at the beginning it will include some comments that describe the conditions that configuration applies to. You can also get the same information by looking at the corresponding configuration file in `shasta/conf`.

The documentation also includes [a table](https://paoloshasta.github.io/shasta/Configurations.html) that summarizes the assembly configurations currently available and recommended for R9 and R10 reads. I plan to keep this table updated as new configurations are added.

**Comment by JMencius** [comment]
Simply use "R10" in the configuration name will be great. Yep, that command really helps.
