### ISSUE TITLE
Unusual performance on R10.4 Dorado data

### ISSUE THREAD

**Issue by Mon3trK** [paoloshasta/shasta#24]
Dear @paoloshasta ,
  Hi, recently I am assembling a human genome sequenced by R10.4.1 flowcell and basecalled with Dorado (HAC mode). The N50 of the input read is not bad for ~32.0K and the sequencing depth is also decent (~40-50X). I use the command 
```bash 
shasta-Linux-0.11.1 --input {FASTQ_FILE} --config Nanopore-R10-Fast-Nov2022 --threads 80 --assemblyDirectory {OUTPUT_DIR};
```
to conduct the denovo assembly. But I only got a NG50 of ~3 Mb and total length of 2.7 Gb. The performance of shasta on this data is unusual I think, do you hae any ideas to improve this assembly?
Many thanks

**Comment by paoloshasta** [comment]
Please attach the following files from the assembly directory:

```
AssemblySummary.html
stdout.log
Binned-ReadLengthHistogram.csv
LowHashBucketHistogram.csv
DisjointSetsHistogram.csv
Assembly-BothStrands.gfa
```

You can omit the last one if it is too big and it is not practical to upload it. With this I should be able to get some idea of what may be going on.

**Comment by Mon3trK** [comment]
Hi @paoloshasta, I have sent the files through email. If you have any further question please let me know

**Comment by paoloshasta** [comment]
I received your files and I am looking at them. However, when I try to reply to your e-mail, I get in a return an error message from your Outlook server. Please contact me again using a different e-mail address so I can reply. You don't need to resend the files - I have them.

**Comment by Mon3trK** [comment]
Hi @paoloshasta thank you for your help, my different e-mail is 22110700054@m.fudan.edu.cn

**Comment by Mon3trK** [comment]
Thanks to @paoloshasta I successfully solved the problem. For ONT `R10` data, to achieve the best performance, one should use `Guppy5/6` for basecalling under the `sup` basecalling mode if you choose the `--config Nanopore-R10-Fast-Nov2022`. Baecalling with `hac` or `Dorado` are suboptimal for this configuration.

**Comment by colindaven** [comment]
Hi @Mon3trK , for what it's worth that is not generally true for our datasets, and we have done >20 plant genomes.

We use `dorado` and sup basecalling as standard, and `--config Nanopore-R10-Fast-Nov2022` generally yields best results. If we see poor results, which is rare these days, then we go back to the `Nanopore-May2022` config. 

I believe guppy is deprecated in favour of dorado so it won't be a good choice for the future.

**Comment by Mon3trK** [comment]
Hi @colindaven thank you for the heads up.
