### ISSUE TITLE
Feature request: support for multiple reads types, e.g. duplex Q30 reads

### ISSUE THREAD

**Issue by osilander** [paoloshasta/shasta#3]
Is it possible to support two read types, e.g. Q20+ simplex and Q30 duplex reads? For example supplied in two files?

**Comment by paoloshasta** [comment]
Shasta was designed, for performance considerations and for other reasons, to work with a homogeneous set of input reads. Supporting hybrid assemblies would require a complete redesign, as well as significant algorithmic rework. Therefore I am sorry to say this will not be possible.

For hybrid assembly, in some situations it might make sense to use one read type for assembly and the second read type for polishing. But that depends on coverage and other factors, and I am not sure it would be a good choice for your situation. 

None of the existing assembly configurations support R10 reads like the ones you describe. The most recent assembly configuration (`Nanopore-May2022`) is optimized for R9 reads created by Guppy 5 or 6 with "super" accuracy. I am working on creating assembly configurations for R10 simplex reads ("Q20", both fast mode and slow mode). These should become available soon as part of a new Shasta release. Assembly configurations for duplex reads will come a bit later.

**Comment by paoloshasta** [comment]
See #1 for assembly configurations for R10 I just added. They can be used now with Shasta 0.10.0 by downloading the configuration files. In the next release they will be accessible as built-in assembly configurations.

**Comment by osilander** [comment]
This is great, thanks for such a quick followup.
