### ISSUE TITLE
hugepages permission denied on x1.32xlarge

### ISSUE THREAD

**Issue by qqwang-berkeley** [paoloshasta/shasta#31]
Hi Paolo,

Thank you for developing the shasta tool. I tried to use it to de-novo assemble a mouse genome from ONT sequencing data, and requested the exact AWS instance as recommended, which in theory should give me root privilege. However, when I ran the optimal memory setting, the following error still occurred:

sh: 1: cannot create /sys/kernel/mm/hugepages/hugepages-2048kB/nr_overcommit_hugepages: Permission denied
Error 512: Unknown error 512 running command: sudo sh -c "echo 979636 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_overcommit_hugepages"

Any recommendations to fix this error?

Thank you!

**Comment by paoloshasta** [comment]
What operating system is the instance running? Did you login as user `ubuntu`? 

If you are still getting a failure, please post the output of the following commands:

```
uname -a
lsb_release -a
head -1 /proc/meminfo
sudo -l
```

**Comment by paoloshasta** [comment]
Also, AWS now provides more efficient instances than `x1.32xlarge` for the same cost: `x2iedn.16xlarge` and `x2idn.32xlarge`, both with 2 TB of memory and the same hourly cost as `x1.32xlarge`.

**Comment by qqwang-berkeley** [comment]
Here are the outputs:

> uname -a
5.15.0-1064-aws #70-Ubuntu SMP Thu Jun 13 16:12:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

> head -1 /proc/meminfo
MemTotal:        3881244 kB

> sudo -l
env_reset, mail_badpass, secure_path=/usr/local/sbin\:/usr/local/bin\:/usr/sbin\:/usr/bin\:/sbin\:/bin\:/snap/bin
    (root) NOPASSWD: ALL

**Comment by paoloshasta** [comment]
I think the problem is that you are logged in as user `chanzuckerberg#70-Ubuntu`. To get full `sudo` privilege, you need to login as user `ubuntu`. Here is the output of `sudo -l` for me when I am logged in as user `ubuntu`:

```
sudo -l
Matching Defaults entries for ubuntu on ip-172-31-35-77:
    env_reset, mail_badpass,
    secure_path=/usr/local/sbin\:/usr/local/bin\:/usr/sbin\:/usr/bin\:/sbin\:/bin\:/snap/bin,
    use_pty

User ubuntu may run the following commands on ip-172-31-35-77:
    (ALL : ALL) ALL
    (ALL) NOPASSWD: ALL
```

Under these conditions you can still run Shasta, but at decreased performance. Just omit the `--memoryMode` and `--memoryBacking` options from your command line.

**Comment by qqwang-berkeley** [comment]
Yes I totally agree with you. I was able to run Shasta with default memory setting without root privilege, and it did complete < 4hrs. I will also try the other two AWS instances as you recommended. Thank you!
