### ISSUE TITLE
assembly mode2 with "corrected" reads instead of assembly mode 3?

### ISSUE THREAD

**Issue by jelber2** [paoloshasta/shasta#32]
Hi, 
I was wondering if there might be a recommendation on using herro corrected reads with assembly mode 2, as opposed to just blindly using config `Nanopore-Phased-R10-Fast-Nov2022` and `--Kmers.k 30` (which seems to be used with `Nanopore-ncm23-May2024`), and maybe report back. I tried these reads with `Nanopore-ncm23-May2024` and seemed to get good results, but I was curious about getting a haploid assembly that comes along with `Nanopore-Phased-R10-Fast-Nov2022` too.

**Comment by paoloshasta** [comment]
We are working on assembly configurations for phased assembly with the latest ONT reads as per ONT's May 2024 announcements. We plan to release assembly configurations for both raw reads and Herro-corrected reads. These will use the new Shasta Mode 3 assembly, not Mode 2 assembly. The combination of longer and more accurate reads with new assembly methods in Mode 3 assembly will deliver assemblies with significant improvements in accuracy, contiguity, and completeness. Assembly performance (speed) will not change significantly. I cannot make any promises regarding timing but I hope it will be soon.

**Comment by jelber2** [comment]
I guess you just pushed those assembly configurations?

**Comment by paoloshasta** [comment]
We hope to release 0.13.0 today. There will also be a brief presentation summarizing results.

**Comment by paoloshasta** [comment]
We released Shasta 0.13.0 today. See the release notes and [these slides](https://paoloshasta.github.io/shasta/Shasta-0.13.0.pdf).
