### ISSUE TITLE
filesystem error: cannot create directory: Permission denied [ShastaRun]

### ISSUE THREAD

**Issue by handesome** [paoloshasta/shasta#39]
Hi! Thank you for developing the shasta!when I run
`./shasta-Linux-0.11.1 --input /data/work/SRR17180611.fasta --config Nanopore-May2022
Shasta Release 0.11.1
2024-Oct-16 15:11:50.127747 filesystem error: cannot create directory: Permission denied [ShastaRun]`
I'm a beginner,could anyone give some suggestion?Thanks!

**Comment by kokyriakidis** [comment]
Hi @handesome!

If you do not specify the output assembly directory, Shasta will try to write it's output to a folder named `ShastaRun` in your currect working directory. As @colindaven said, probably you do not have permissions to write in your currect working directory.

You can add the option `--assemblyDirectory` to specify where to store the output of Shasta.

**Comment by handesome** [comment]
Hi！Thank you for quick reply!Now I got it!Thanks again!
