### ISSUE TITLE
--Reads.desiredCoverage does to work when RLE is turned off

### ISSUE THREAD

**Issue by paoloshasta** [paoloshasta/shasta#4]
The `--Reads.desiredCoverage` command line option causes Shasta to crash when the Run-Rength Encoding (RLE) representation of the reads is not used (that is, `--Reads.representation` is 0). This was first reported by @colindaven in #1.

RLE is turned off in all 4 assembly configurations for ONT R10 reads, so `--Reads.desiredCoverage`  will not work when using one of those configurations.

**Comment by paoloshasta** [comment]
`--Reads.desiredCoverage` does work correctly when RLE is in use, which is the case for most Shasta assembly configurations, with the notable exception of the 4 new ones for R10 reads.

**Comment by paoloshasta** [comment]
Fixed by commit 356c004880718892067ea69ffec64a1ddcc62335. The fix will be in the next release.

**Comment by paoloshasta** [comment]
This fixed in [Shasta 0.11.1](https://github.com/paoloshasta/shasta/releases/tag/0.11.1).

**Comment by colindaven** [comment]
Thanks, can confirm this works for me now. If set incorrectly, the error in the log is understandable.
